const axios = require('axios');
const Product = require('../models/Product');

function getApiKey() { return process.env.AI_API_KEY; }

// ─── AI-powered SEO generation (full control) ──────────────
async function generateSEO(product) {
  if (!product || !product._id) return null;

  const apiKey = getApiKey();
  if (!apiKey) return fallbackSEO(product);

  const { name, brand, categories, mainPrice, discountPrice, gender, averageRating, totalReviews, description, variants } = product;
  const catStr = Array.isArray(categories) ? categories.join(', ') : 'N/A';
  const price = discountPrice || mainPrice || 'N/A';
  const desc = description || (Array.isArray(variants) ? variants[0]?.description : '') || '';

  const prompt = `You are Barvella's head of SEO. Generate SEO metadata for the following product. You have FULL creative control — craft compelling, click-worthy meta that will rank high on Google and convert shoppers.

Return ONLY a valid JSON object with these exact keys:
- metaTitle: A compelling product title (max 70 chars, include brand and key feature, end with "| Barvella")
- metaDescription: A persuasive product description (max 170 chars, include price, benefit, and call-to-action)
- metaKeywords: A comma-separated list of 12-20 relevant keywords (include product name, brand, category, variants, use cases, and "Barvella", "Bangladesh", "buy online")

Product data:
- Name: ${name}
- Brand: ${brand || 'N/A'}
- Category: ${catStr}
- Price: BDT ${price}
- Gender: ${gender || 'Unisex'}
- Rating: ${averageRating || 'N/A'} (${totalReviews || 0} reviews)
- Description: ${(desc || 'N/A').slice(0, 300)}
- Variant colors: ${(Array.isArray(variants) ? variants.map(v => v.colorName).filter(Boolean).join(', ') : 'N/A') || 'N/A'}

Example output format:
{"metaTitle":"Nike Air Max 270 — BDT 12,500 | Barvella","metaDescription":"Shop Nike Air Max 270 at BDT 12,500. Comfortable, stylish sneakers with air cushioning. Fast delivery across Bangladesh. Order now!","metaKeywords":"nike air max 270, nike shoes, air max, buy nike Bangladesh, ..."}

Rules:
- metaTitle must be ≤70 characters
- metaDescription must be ≤170 characters
- Be creative and persuasive — this is marketing copy, not a data sheet
- Include price and brand where relevant
- End metaTitle with "| Barvella"`;

  try {
    const res = await axios.post(
      process.env.AI_API_URL || 'https://api.openai.com/v1/chat/completions',
      {
        model: process.env.AI_MODEL || 'gpt-4o-mini',
        temperature: 0.7,
        max_tokens: 400,
        messages: [{ role: 'user', content: prompt }],
      },
      { headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' }, timeout: 20000 }
    );
    const text = res?.data?.choices?.[0]?.message?.content?.trim();
    if (!text) return fallbackSEO(product);
    const cleaned = text.replace(/```json|```/g, '').trim();
    const json = JSON.parse(cleaned);
    const seo = {
      metaTitle: String(json.metaTitle || fallbackMetaTitle(product)).slice(0, 70),
      metaDescription: String(json.metaDescription || fallbackMetaDescription(product)).slice(0, 170),
      metaKeywords: json.metaKeywords || fallbackMetaKeywords(product),
      ogImage: product.mainImage || '',
      autoGenerated: true,
      lastGenerated: new Date(),
    };
    await Product.updateOne({ _id: product._id }, { $set: { seo } });
    return seo;
  } catch (err) {
    console.error('AI SEO failed, using fallback:', err.message);
    return fallbackSEO(product);
  }
}

// ─── Emergency fallback (only when AI is unavailable) ───────
function fallbackMetaTitle(p) {
  return `${p.brand ? p.brand + ' ' : ''}${p.name}${p.discountPrice || p.mainPrice ? ' — BDT' + (p.discountPrice || p.mainPrice) : ''} | Barvella`.slice(0, 70);
}
function fallbackMetaDescription(p) {
  const price = p.discountPrice || p.mainPrice;
  return `Shop ${p.brand ? p.brand + ' ' : ''}${p.name}${price ? ' at BDT' + price : ''}. ✓ Authentic ✓ Fast delivery ✓ Easy returns. Order from Barvella now!`.slice(0, 170);
}
function fallbackMetaKeywords(p) {
  const parts = [p.name, p.brand, ...(Array.isArray(p.categories) ? p.categories.flat().filter(Boolean) : []), p.gender, 'Barvella', 'buy online', 'Bangladesh'].filter(Boolean);
  return [...new Set(parts.map(s => String(s).toLowerCase().trim()))].join(', ');
}
function fallbackSEO(product) {
  const seo = {
    metaTitle: fallbackMetaTitle(product),
    metaDescription: fallbackMetaDescription(product),
    metaKeywords: fallbackMetaKeywords(product),
    ogImage: product.mainImage || '',
    autoGenerated: true,
    lastGenerated: new Date(),
  };
  Product.updateOne({ _id: product._id }, { $set: { seo } }).catch(() => {});
  return seo;
}

// ─── Batch operations ──────────────────────────────────────
async function generateSEOAll(batchSize = 10) {
  const cursor = Product.find({ $or: [{ seo: { $exists: false } }, { 'seo.autoGenerated': { $ne: true } }, { 'seo.lastGenerated': null }] }).cursor();
  let count = 0, buffer = [];
  for await (const product of cursor) {
    buffer.push(product);
    if (buffer.length >= batchSize) {
      await Promise.all(buffer.map(p => generateSEO(p)));
      count += buffer.length; buffer = [];
    }
  }
  if (buffer.length > 0) { await Promise.all(buffer.map(p => generateSEO(p))); count += buffer.length; }
  return count;
}

async function forceRegenerateAll() {
  const products = await Product.find({}).limit(500).lean();
  let count = 0;
  for (const product of products) { await generateSEO(product); count++; }
  return count;
}

async function getSEOStats() {
  const total = await Product.countDocuments();
  const withSEO = await Product.countDocuments({ seo: { $exists: true, $ne: null } });
  return { total, withSEO, pending: total - withSEO };
}

module.exports = { generateSEO, generateSEOAll, forceRegenerateAll, getSEOStats };
